name: panns
channels:
  - anaconda
  - defaults
dependencies:
  - ca-certificates=2025.7.15=hecd8cb5_0
  - libcxx=19.1.7=haebbb44_3
  - libffi=3.4.4=hecd8cb5_1
  - ncurses=6.5=h923df54_0
  - openssl=3.0.17=hee2dfae_0
  - pip=24.2=py38hecd8cb5_0
  - portaudio=19.6.0=h6d0c2b6_5
  - python=3.8.20=hce00570_0
  - readline=8.3=h49f2429_0
  - setuptools=75.1.0=py38hecd8cb5_0
  - sqlite=3.50.2=hc8b0dd6_1
  - tk=8.6.15=h3a5a201_0
  - wheel=0.44.0=py38hecd8cb5_0
  - xz=5.6.4=h46256e1_1
  - zlib=1.2.13=h4b97444_1
  - pip:
      - antlr4-python3-runtime==4.8
      - audioread==3.0.1
      - certifi==2025.11.12
      - cffi==1.17.1
      - charset-normalizer==3.4.4
      - cycler==0.12.1
      - decorator==5.2.1
      - idna==3.11
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - librosa==0.11.0
      - llvmlite==0.41.1
      - matplotlib==3.4.0
      - msgpack==1.1.1
      - numba==0.58.1
      - numpy==1.24.4
      - omegaconf==2.1.1
      - packaging==25.0
      - pillow==8.4.0
      - platformdirs==4.3.6
      - pooch==1.8.2
      - pyaudio==0.2.11
      - pycparser==2.23
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.3
      - requests==2.32.4
      - resampy==0.4.3
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - six==1.17.0
      - soundfile==0.13.1
      - soxr==0.3.7
      - threadpoolctl==3.5.0
      - torch==1.4.0
      - torchlibrosa==0.0.5
      - typing-extensions==4.13.2
      - urllib3==2.2.3
      - zipp==3.20.2
prefix: /Users/liangzining/miniconda3/envs/panns
